#Config File example
save_dir: /project/train/models
model:
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998
  arch:
    name: OneStageDetector
    backbone:
      name: ShuffleNetV2
      model_size: 1.0x
      out_stages: [4]
      activation: LeakyReLU
    fpn:
      name: CenternetDeconv
      deconv_channels: [464, 232, 116, 64]
      deconv_kernel: [4, 4, 4]
    head:
      name: NanoDetHead
      num_classes: 1
      input_channel: 64
      feat_channels: 64
      stacked_convs: 3
      share_cls_reg: True
      octave_base_scale: 8
      scales_per_octave: 1
      strides: [4]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0

class_names: &class_names ['rat']  #Please fill in the category names (not include background category)
data:
  train:
    name: XMLDataset
    class_names: *class_names
    img_path: /home/data/ #Please fill in train image path
    ann_path: /home/data/  #Please fill in train xml path
    input_size: [960,544] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      flip: 0.5
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: XMLDataset
    class_names: *class_names
    img_path: /home/data/ #Please fill in val image path
    ann_path: /home/data/ #Please fill in val xml path
    input_size: [960, 544] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0] # Set like [0, 1, 2, 3] if you have multi-GPUs
  workers_per_gpu: 8
  batchsize_per_gpu: 24
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: AdamW
    lr: 0.001
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  total_epochs: 20
  lr_schedule:
    name: MultiStepLR
    milestones: [5,12,17]
    gamma: 0.1
    # name: CosineAnnealingLR
    # T_max: 20
    # eta_min: 0.00005
  val_intervals: 10
grad_clip: 35
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10
  log_savedir: /project/train/log
